icons = "awesome"

[theme]
name = "solarized-dark"
[theme.overrides]
separator = ""

[[block]]
block = "focused_window"
max_width = 50

[[block]]
block = "sound"

[[block]]
block = "cpu"
interval = 5

[[block]]
block = "memory"
interval = 5
format_mem = "{Mup}%"
format_swap = "{SUp}%"

[[block]]
block = "disk_space"
path = "/"
alias = "/"
interval = 20
warning = 20.0
alert = 10.0

[[block]]
block = "net"
device = "wlp3s0"
ip = true
speed_up = false
speed_down = false
interval = 5

[[block]]
block = "battery"
interval = 10
format = "{percentage}% {time}"

[[block]]
block = "time"
interval = 60
format = "%a %d.%m.%Y %R"
